#!/bin/bash

# Ensure minikube is started
minikube start --driver=docker

# Install test k8s resources
minikube kubectl -- apply -f k8s/

# wait for services to be ready
echo "Waiting for services to be online..."
minikube kubectl -- wait --for=condition=available --timeout=120s deployment/api-test

export TEST_PRIVATE_KEY_BASE64="LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBM3RRMkhna01LWFdqUkhGdXdYaXlyc0U4Z1pDTGduNUJJNlF6UDZ3aEZNZU1zK3AyClUzdGdsQ1hZTDVFanJYdkNtMGNVajhJanc5eFJNMnhYdVV1Sys0dFZtVlByNEJkWjNNYjVkcktmVzEzU1F2enoKemJ1cmQ4L21OOU50eXdFaGlPOGJUZmdZR0JCVVBjRkJ3eDNvcGVidXV0VENGVjB5WlIrTEc3SysxYXVkUVhEOAp5RWEzMFYwWlpOSHVYeUwxaE16RURDRk45NElsZGlnM0xLRzUvMHc2ZWFhVGZBaEZwNFBVeVBNMXk5MlRtczMxCkFGTXZ2VFVyenBLQmFhZmpTcDhEVkVocVdXQzdackx1Z2hNVDNhdVZsT1VqK04wMDZhd0lGdmg2dEpVVWRDbEgKUGRRK1FJNDlRNnFFbStZZTIySjZ2YjhRNGUrdmtNSUxzTE5hZlFJREFRQUJBb0lCQUI2aGkyTHJtWGxsaTNFUQpLc3A3dmd4WjBlaDVwMFBqK1M1ZUZ4RnNwd3VGTnVsUWxMMTdHMWFpTVNxd3gvZkVLSWRSNlJpdDlsNnBQWnhWCkMyWVVaV0dZME1hSUM4ZTlUZ1FVY2h5SUIzSDIzcjJJcWpjZzBqeGhIdU9UcytjUkc3d0lLbmU0WUErR3h4M0sKSURFalBtVDM3dDlOK2ZRWDRLS1lDSFpoUnV4MkxoOXlrNDdUcEV6eS9PQmpkUUdmVktrZVFReEM1aUtwdDExVApPbTZPbHhNekdZVHA4My85N3lNUFo1VXhzcW13ZGdrYXV4b3pYS0t3eis5bjQ1ajZhVzdpNU5mTDlzNUxvZzduCmZtb0JLRWtZUnBwdzZKbW1WSTg0MDJraHRhRit6dytWbXdlZ2JYcFoyRjR2SlB3N1NrUjNsMnZJMDFMb1ZUTysKalpOanNuMENnWUVBL0VwUGdjL2c5MHpOY2dOWFhVaDlzZUJlNEtDYUh4K3Z2SjY2NWgvaEN3eU1pbUtSV2o2eQp1WFRYUzdTQWJlYThyaS94VFRsREhuZGhURjZnOUREc0VoakF0aWxiSzI2ei8yMk5ZcjZrRHVDYnZTRlN4VGZxCmt3ZEZIQnZ5dWV0dGFsRTJOcWEwaUU5a3ZxUGZNNTN3cU8vcHM5aVFvbU1WMzIwL0pPcjNLNjhDZ1lFQTRoc0EKRjJPYkFBTEc1a2g5Mmc3OStKVXpZQUo1dXgzMDltLzV6L1kvSGVQd1pxSmtzUVBIaFVzQzJGZjA5VzlYTGJoYgo3TVlPRlQvZ1BwRms2NjRsL3dWNUplZlFSZEI5dVY5Q0dGTEd1MFVxYzVVbEcvMFQvS0VsM0FwVjFoQkVqRUtXCkEyWVFseVUyQ0xtcXFWcnRvYzBTRmFkZWwvMlJVaFZBNGNYWFM1TUNnWUFwV0RRM1hjM01PVFhoM1ZKUDR6VlcKRlNMM1JOcDlCMEJSZE9IRUhLMVFsam5oNDgxV01MZ3hWRWlFQzR5UWRpT3RtQVcvVmdiOTB5cUt6V2NySFdsUwpmZVAyOWtnT2toSEZaanFwVi95aXc0UkNObGZPSWgrN0FKSCt6VVcxMmpNUUhVYjVKZENvRmZxNGt6cGN4eUZOClRpUEthVThxalhwa0p3OFdDYnQvMlFLQmdRQzhKUWVRYnR2ZHlISEYwZkNYY1A0NHliNTBWOXIvcjAvVmVSd0EKeHNHQ2w5ZkZMOEJsNCtVMHIxUnd2ZEFpSTBJQjAzVDZzMXVvcHZ4c1ZBUU1jVjlBdEVjNUdZcWZiWHdRc29tSApQK29LanVWaVJHc2F2UjdTaXkyN3lnWGZHSzVSb0Y2LytVQTQ1VWZ2UHNBYUtJV3dxN291dHBUcUdKL0NFOWxuCmhYOC9iUUtCZ0JWbWtLL0dIaFV4MThhbXZRdjcvRlJvOVJJQWRrelk0Mm9xTUcvdzZxTmhjQmIxcDhRa2xENGcKT2RyL0U3L0xhNk1Ma0FHUkZuUml3L01ZRkFBZFBnYnVaNldhc0J4dzZrcTBlbFZZVktlNjJDdjlRM2w3MHB5UQpxUzUzMHc1Q1kvNmxXbkkvbENVRVdxVnV5RWtWei9hQU1aY0JTSjRCVE5vQU43aGQreTliCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="

# run migrations
minikube kubectl -- exec -it service/api-test -- /usr/bin/env DATABASE_URL="postgresql://postgres:1234@localhost:5432/postgres?serverVersion=13&charset=utf8" /application/bin/console doctrine:schema:drop --full-database --force
minikube kubectl -- exec -it service/api-test -- /usr/bin/env DATABASE_URL="postgresql://postgres:1234@localhost:5432/postgres?serverVersion=13&charset=utf8" /application/bin/console doctrine:migrations:migrate --no-interaction
minikube kubectl -- exec -it service/api-test -- /usr/bin/env DATABASE_URL="postgresql://postgres:1234@localhost:5432/postgres?serverVersion=13&charset=utf8" /application/bin/console esa:create-transport "test-transport" "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzdFEySGdrTUtYV2pSSEZ1d1hpeQpyc0U4Z1pDTGduNUJJNlF6UDZ3aEZNZU1zK3AyVTN0Z2xDWFlMNUVqclh2Q20wY1VqOElqdzl4Uk0yeFh1VXVLCis0dFZtVlByNEJkWjNNYjVkcktmVzEzU1F2enp6YnVyZDgvbU45TnR5d0VoaU84YlRmZ1lHQkJVUGNGQnd4M28KcGVidXV0VENGVjB5WlIrTEc3SysxYXVkUVhEOHlFYTMwVjBaWk5IdVh5TDFoTXpFRENGTjk0SWxkaWczTEtHNQovMHc2ZWFhVGZBaEZwNFBVeVBNMXk5MlRtczMxQUZNdnZUVXJ6cEtCYWFmalNwOERWRWhxV1dDN1pyTHVnaE1UCjNhdVZsT1VqK04wMDZhd0lGdmg2dEpVVWRDbEhQZFErUUk0OVE2cUVtK1llMjJKNnZiOFE0ZSt2a01JTHNMTmEKZlFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="

# ensure test runner is started
minikube kubectl -- wait --for=condition=available --timeout=120s deployment/behavioral-tests

# copy tests to runner
minikube kubectl -- exec deploy/behavioral-tests -- mkdir -p behavioral
tar cf - behavioral | minikube kubectl -- exec -i  deploy/behavioral-tests -- tar xf - -C ./

# Run tests
minikube kubectl -- exec -it deploy/behavioral-tests -- /bin/bash -c "cd behavioral && npm install && ./node_modules/.bin/cucumber-js features/ -r steps/ --publish-quiet"
