Feature: Private streams can be joined with an invite generated by another user.

  Scenario: Trying to join a private stream without an invite should fail
    Given There are two users, User "A" and User "B"
    And User "A" created private root stream "A"
    When User "B" joins the stream named "A" created by User "A"
    Then User "B" has no streams

  Scenario: Trying to join a private stream with an invite should succeed
    Given There are two users, User "A" and User "B"
    And User "A" created private root stream "A"
    And User "A" created an invite for stream "A"
    When User "B" joins the stream named "A" created by User "A" with their invite
    Then User "B" will have a stream named "A"
