Feature: Private streams can be joined with an invite generated by another user.

  Scenario: Trying to join a private stream without an invite should fail
    Given There are two users, User "i_A" and User "i_B"
    And User "i_A" created private root stream "i_A"
    When User "i_B" joins the stream named "i_A" created by User "i_A"
    Then User "i_B" has no streams

  Scenario: Trying to join a private stream with an invite should succeed
    Given There are two users, User "i_A" and User "i_B"
    And User "i_A" created private root stream "i_A"
    And User "i_A" created an invite for stream "i_A"
    When User "i_B" joins the stream named "i_A" created by User "i_A" with their invite
    Then User "i_B" will have a stream named "i_A"
